### ISSUE TITLE
Requirement is pinned for devolo-home-control-api 0.11.0: websocket-client<=0.56.0

### ISSUE THREAD

**Issue by MartinHjelmare** [2Fake/devolo_home_control_api#53]
**Describe the bug**
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**To Reproduce**
```
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pip install -r requirements_all.txt
...
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pipdeptree --reverse --packages websocket-client
...
websocket-client==0.54.0
  - devolo-home-control-api==0.11.0 [requires: websocket-client<=0.56.0]
...
```

**Expected behavior**
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 0.11.0

**Comment by 2Fake** [comment]
@MartinHjelmare  Thanks for the hint, but we can not use the latest version of the websocket client, because of this bug, which is not fixed yet. https://github.com/websocket-client/websocket-client/issues/604

**Comment by MartinHjelmare** [comment]
Maybe it's possible to work around that bug by passing the `connection` keyword argument when creating the connection as mentioned in the linked issue?

**Comment by 2Fake** [comment]
Yes, this is possible. Thanks for the hint!
