### ISSUE TITLE
Timezone not respected for last_activity

### ISSUE THREAD

**Issue by Shutgun** [2Fake/devolo_home_control_api#59]
**Describe the bug**
The last_activity attribute of the binary sensor property is two hours ahead. That seems to me, that the timestamps the gateway send are in local time but converted as if they were UTC.

**To Reproduce**
1. Have a device with a binary sensor
2. Compare last_activity attribute with the mydevolo web-UI

**Expected behavior**
Both are equal.

**Comment by 2Fake** [comment]
Should be easy to fix with an additional mydevolo timezone api call.
